site_name: redy doc
site_url: https://pugur.github.io/redy_doc/
nav:
  - index.md
  - install.md
  - Cording Tutorials:
    - Hello World: tutorials/0001_helloworld.md
    - Data Types and Variables: tutorials/0002_data_types_and_variables.md
    - Print Formatted: tutorials/0003_print_formatted.md
    - Simple Fizz Buzz Program: tutorials/0004_simple_fizz_buzz_program.md

docs_dir: src
theme:
  name: material
  favicon: assets/theme/logo_r.svg
  logo: assets/theme/logo_r.svg
  language: en
  features:
    - content.code.copy
    - content.code.select
    - navigation.footer

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/pugur523
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/p523n
    # TODO: discord server
    # - icon: fontawesome/brands/discord
    #   link: https://discord.gg/
copyright: Copyright &copy; 2025 pugur

extra_css:
  - assets/css/style.css

# extra_javascript:
  # - assets/js/copy_button.js
  # - assets/js/highlight.js
  # - assets/js/redy.js

plugins:
  - search:
  - i18n:
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: ja
          name: 日本語
          build: true

markdown_extensions:
  - codehilite:
      guess_lang: false
  - admonition
  - toc:
      permalink:
  - pymdownx.highlight:
      use_pygments: true
      pygments_lang_class: true
      line_spans: __span
      anchor_linenums: false
      auto_title: false
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.superfences:
      custom_fences:
        - name: redy
          class: redy
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: ry
          class: redy
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
